version: "3"

services:
  nextcloud:
    image: nextcloud:latest
    restart: always
    links:
      - "db:mariadb"
    volumes:
      - nextcloud:/var/www/html
      - data:/var/www/html/data
      - apps:/var/www/html/custom_apps
      - theme:/var/www/html/themes
    ports:
      - "8080:80"
    env_file:
      - "./env/.nextcloud.env"
    container_name: nextcloud
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql/
      - db_log:/var/log/mysql/
    container_name: mariadb
    env_file:
      - "./env/.mysql.env"

volumes:
  nextcloud:
  data:
  apps:
  theme:
  db_data:
  db_log:
